version: "3.8"
services:
    db:
        container_name: Webapp-DB
        build: ./database
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        ports:
            - 3306:3306 
        environment:
            - MYSQL_ROOT_PASSWORD=1
    web:
        container_name: Webapp-Web
        build: ./Webapp
        restart: unless-stopped
        ports:
            - 80:80
        volumes:
            - ./Webapp/web:/var/www/html
        environment:
            - MYSQL_HOSTNAME=db
            - MYSQL_DATABASE=appdatabase
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=Password@123