---
# tasks file for webapp

- name: Ensure the destination directory exists
  file:
    path: "{{ ansible_env.HOME }}/app"
    state: directory

- name: Copy Webapplication directory to remote host
  copy:
    src: files/Webapplication/
    dest: "{{ ansible_env.HOME }}/app/"
    mode: '0755'
    directory_mode: '0755'

- name: Run Docker Compose
  command: docker compose up -d
  args:
    chdir: "{{ ansible_env.HOME }}/app"